# J2KB 서브젝트 5주차 주제 : Numpy

Numpy는 Numerical Python의 줄임말로, 고성능의 수치계산을 위해 제작된 파이썬 라이브러리입니다.

Numpy는 지난 3~4주차에서 학습했던 벡터 및 행렬을 연산하는 데 있어서 매우 편리한 기능들을 제공하며

데이터 분석에 사용되어지는 라이브러리인 Pandas와 Matplotlib의 기초제로 활용됩니다.

**이번 J2KB 서브젝트 5주차에서는 다양한 Numpy 문법들을 살펴보고, 마지막에는 조금 색다른 실험까지 해봅시다.**

In [1]:
# Numpy의 시작은 import부터
import numpy as np

In [2]:
# np.array()를 사용하기 위해, 우선 데이터 리스트부터 정의를 내린다

data1 = [1,2,3,4,5]
print(data1)

data2 = [1.1,2.2,4.4,6.6,9.9]
print(data2)

[1, 2, 3, 4, 5]
[1.1, 2.2, 4.4, 6.6, 9.9]


In [3]:
# Numpy를 이용하여 array를 정의해보자. 위에서 만든 파이썬 리스트를 활용하여 다음과 같이 쓸 수 있다
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [4]:
# 또는 괄호 안에 직접 리스트를 넣어줘도 가능하다
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [5]:
# array의 형태는 다음 코드로 확인해볼 수 있다

print(arr1.shape)
print(arr2.shape)

(5,)
(5,)


In [6]:
# array의 자료형은 다음 코드로 확인해볼 수 있다

print(arr1.dtype)

int32


In [7]:
# 한편, 실수로 구성된 리스트일 경우는?

arr3 = np.array(data2)
arr3

array([1.1, 2.2, 4.4, 6.6, 9.9])

In [8]:
# 형태와 자료형이 다음과 같이 나타난다
print(arr3.shape)
print(arr3.dtype)

(5,)
float64


In [9]:
# 이러한 경우도 있다

arr4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
print(arr4.shape)
print(arr4.dtype)

(4, 3)
int32


데이터의 형태를 나타내는 ~.shape 부분을 잘 보면 arr1.shape의 결과는 (5,)으로 나타나는데

사실 arr1은 한 행으로 이루어진 행벡터이므로 1차원 데이터이고, 5라는 크기를 가짐을 알 수 있다.

반면 arr4의 경우는 행과 열의 수(각각 4,3)가 모두 나타난 행렬로서 2차원 데이터이고, 12라는 크기를 가짐을 알 수 있다.

자료형(dtype) 쪽도 살펴볼 내용이 있다.

아까 int32와 float64가 출력 결과로 나왔을 것이다.

int32는 모든 원소가 부호가 있는 정수로만 구성된 데이터일 때의 dtype이며, float64는 단 하나라도 실수인 원소를 가지는 데이터가 있을 때의 dtype이다.

예를 들어 **[1, 2.5, 3, 4.1]**로 구성된 데이터는 **1과 3이 정수라고 해도 자료형은 float64로 나오게 된다.**

In [11]:
# 직접 해봤더니, 정수인 원소도 자동으로 실수형으로 변환되었네요

arr5 = np.array([1,2.5,3,4.1])
arr5

array([1. , 2.5, 3. , 4.1])

In [12]:
print(arr5.shape)
print(arr5.dtype)

(4,)
float64


**그 밖에도 Numpy에서 나올 수 있는 자료형은 다양하게 존재한다.**

- 부호가 없는 정수 uint
- 복소수 complex
- 불리언 bool (True, False)
- 문자열 string

이번에는 Numpy에서 array를 정의할 때 사용되는 세 개의 함수인

**np.zeros(), np.ones(), np.arange()** 에 대해서 알아보도록 하자.

In [13]:
# 모든 성분을 실수형 0으로 만들어주는 np.zeros()
arr6 = np.zeros(5,)
arr6

array([0., 0., 0., 0., 0.])

In [14]:
# 2차원으로 나타내려는 경우는 괄호에 주의하자.
arr7 = np.zeros((4,3))
arr7

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
arr6.dtype

dtype('float64')

In [16]:
arr7.dtype

dtype('float64')

In [17]:
# np,zeros()와 비슷한 방식으로 모든 성분을 실수형 1로 만들어주는 np.ones()도 있다.

arr8 = np.ones(8)
arr8

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
arr9 = np.ones((2,5))
arr9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
# np.arange()는 인자로 받는 값만큼 1씩 증가하는 1차원 array를 만들어주는 함수이다.

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(12,18)

array([12, 13, 14, 15, 16, 17])

In [21]:
# 아래에서 2는 등차수열에서의 등차를 의미한다.
np.arange(1,12,2)

array([ 1,  3,  5,  7,  9, 11])

이제, array 연산을 해 보자.

기본적으로 Numpy에서의 연산은 크기가 서로 같은 array끼리 연산하도록 되어 있다.

또한 같은 위치에 있는 요소들끼리 연산된다.

In [22]:
arr10 = np.array([[1,2,3],[4,5,6]])
arr10

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr11 = np.array([[10,11,12],[13,14,15]])
arr11

array([[10, 11, 12],
       [13, 14, 15]])

In [24]:
# array끼리의 덧셈과 뺄셈

print(arr10 + arr11)
print(arr10 - arr11)

[[11 13 15]
 [17 19 21]]
[[-9 -9 -9]
 [-9 -9 -9]]


In [25]:
# array끼리의 곱셈 - 수학의 행렬곱 계산법이 아닌 동일 요소들끼리의 곱으로 구성된 결과가 나온다.

arr10 * arr11

array([[10, 22, 36],
       [52, 70, 90]])

In [26]:
# array끼리의 나눗셈 - 곱셈과 원리는 동일하나 나누기를 할 때는 결과에 따라 소수점 아래 결과가 나타날 수 있다.

arr11 / arr10

array([[10.  ,  5.5 ,  4.  ],
       [ 3.25,  2.8 ,  2.5 ]])

여기서 Numpy에 심어져 있는 기능인 브로드캐스트에 대해서 알아보려고 한다.

**브로드캐스트란 서로 크기가 다른 array끼리 연산이 가능하게끔 하는 기능을 말한다.**

In [27]:
arr10

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
arr12 = np.array([4,8,12])
arr12

array([ 4,  8, 12])

In [29]:
arr10 + arr12

array([[ 5, 10, 15],
       [ 8, 13, 18]])

In [30]:
arr10 - arr12

array([[-3, -6, -9],
       [ 0, -3, -6]])

In [31]:
arr10 * arr12

array([[ 4, 16, 36],
       [16, 40, 72]])

또한 하나의 array에 스칼라배 연산은 물론, n제곱 연산도 가능하다.

In [32]:
# 스칼라배 연산

arr10 * 7

array([[ 7, 14, 21],
       [28, 35, 42]])

In [33]:
# 3제곱 연산

arr10 ** 3

array([[  1,   8,  27],
       [ 64, 125, 216]], dtype=int32)

이제 array 인덱싱에 대해 알아보자.

In [34]:
# 1차원 array에 대하여

arr13 = np.arange(1,20,2)
arr13

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [38]:
# 인덱싱은 대괄호를 사용한다

print(arr13[0])
print(arr13[6])
print(arr13[2:5])
print(arr13[:])

1
13
[5 7 9]
[ 1  3  5  7  9 11 13 15 17 19]


In [39]:
# 2차원 array에 대하여

arr14 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
arr14

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
# 2차원 array의 인덱싱을 할 때는 2개의 인자를 입력해야 한다
print(arr14[0,0])
print(arr14[1,2])

1
7


In [43]:
# 3행의 모든 요소 출력
arr14[2,:]

array([ 9, 10, 11, 12])

In [44]:
# 모든 행의 2번째 요소 출력
arr14[:,1]

array([ 2,  6, 10])

**array boolean indexing**에 대해서도 알아보자.

In [45]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo','Park','Beomwoo'])
names

array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park',
       'Beomwoo'], dtype='<U7')

In [46]:
names.shape

(8,)

In [55]:
# 아래에서 사용되는 np.random.randn() 함수는 기대값이 0이고, 표준편차가 1인 가우시안 정규 분포를 따르는 난수를 발생시키는 함수이다.
# 이 외에도 0~1의 난수를 발생시키는 np.random.rand() 함수도 존재한다.
data = np.random.randn(8,4)
data

array([[-0.0789954 , -0.39766427, -0.75493207,  0.60607499],
       [-2.26631289,  0.34062206,  1.87825669, -1.39787347],
       [ 1.95551166,  2.11416842,  0.01998946,  0.47224989],
       [ 0.30527631,  1.15799228, -0.05154758,  1.0074178 ],
       [-0.90466377,  1.71879136, -0.46472975, -0.73386946],
       [-0.80495881, -0.64951233, -1.03338874,  2.54299303],
       [ 0.6796653 ,  0.2557452 , -0.65658327, -0.64232121],
       [-0.72199497, -1.09608569,  1.37862023, -0.13585244]])

위와 같은 names와 data라는 array가 있다.

이때, names의 각 요소가 data의 각 행과 연결된다고 가정한다.

그리고 이 때, names가 Beomwoo인 행의 data만 보고 싶을 때 다음과 같이 마스크를 사용해볼 수 있을 것이다.

In [56]:
# 요소가 Beomwoo인 항목에 대한 mask 생성
names_Beomwoo_mask = (names == 'Beomwoo')
names_Beomwoo_mask

array([ True,  True, False, False, False,  True, False,  True])

In [57]:
data[names_Beomwoo_mask,:]

array([[-0.0789954 , -0.39766427, -0.75493207,  0.60607499],
       [-2.26631289,  0.34062206,  1.87825669, -1.39787347],
       [-0.80495881, -0.64951233, -1.03338874,  2.54299303],
       [-0.72199497, -1.09608569,  1.37862023, -0.13585244]])

위의 결과를 보면 요소가 Beomwoo인 것은 0번째, 1번째, 5번째, 7번째이므로, data에서 0,1,5,7행의 모든 요소를 출력한다.

이를 위해 요소가 Beomwoo인 것에 대한 boolean값을 가지는 mask를 만들었고, 마스크를 인덱싱에 응용하여 data의 0,1,5,7행을 출력한 것이다.

In [58]:
# 요소가 Kim인 행의 데이터만 꺼내기
data[names == 'Kim',:]

array([[1.95551166, 2.11416842, 0.01998946, 0.47224989]])

In [59]:
# 논리 연산을 응용하여, 요소가 Kim 또는 Park인 행의 데이터만 꺼내기
data[(names == 'Kim') | (names == 'Park'),:]

array([[ 1.95551166,  2.11416842,  0.01998946,  0.47224989],
       [ 0.6796653 ,  0.2557452 , -0.65658327, -0.64232121]])

물론 data array 자체적으로도 마스크를 만들고, 이를 응용하여 인덱싱이 가능하기도 하다.

data array에서 0번째 열의 값이 0보다 작은 행을 구해 보자.

In [60]:
# 먼저 마스크를 만든다.
# data array에서 0번째 열이 0보다 작은 요소의 boolean 값은 다음과 같다.
# 부등호 판별이기 때문에, 결과는 boolean 값으로 나온다.
data[:,0] < 0

array([ True,  True, False, False,  True,  True, False,  True])

In [61]:
# 위에서 만든 마스크를 이용하여 0번째 열의 값이 0보다 작은 행을 구한다.
data[data[:,0]<0,:]

array([[-0.0789954 , -0.39766427, -0.75493207,  0.60607499],
       [-2.26631289,  0.34062206,  1.87825669, -1.39787347],
       [-0.90466377,  1.71879136, -0.46472975, -0.73386946],
       [-0.80495881, -0.64951233, -1.03338874,  2.54299303],
       [-0.72199497, -1.09608569,  1.37862023, -0.13585244]])

이를 통해 특정 위치에만 우리가 원하는 값을 대입할 수 있다.

위에서 얻은, 0번째 열의 값이 0보다 작은 행의 2,3번째 열의 값에 각각 0을 대입해 보자.

In [62]:
# 0번째 열의 값이 0보다 작은 행의 2,3번째 열의 값
data[data[:,0]<0,2:4]

array([[-0.75493207,  0.60607499],
       [ 1.87825669, -1.39787347],
       [-0.46472975, -0.73386946],
       [-1.03338874,  2.54299303],
       [ 1.37862023, -0.13585244]])

In [63]:
# 0번째 열의 값이 0보다 작은 2,3번째 열의 값에 대해서 모두 0으로 치환
data[data[:,0]<0,2:4] = 0
data

array([[-0.0789954 , -0.39766427,  0.        ,  0.        ],
       [-2.26631289,  0.34062206,  0.        ,  0.        ],
       [ 1.95551166,  2.11416842,  0.01998946,  0.47224989],
       [ 0.30527631,  1.15799228, -0.05154758,  1.0074178 ],
       [-0.90466377,  1.71879136,  0.        ,  0.        ],
       [-0.80495881, -0.64951233,  0.        ,  0.        ],
       [ 0.6796653 ,  0.2557452 , -0.65658327, -0.64232121],
       [-0.72199497, -1.09608569,  0.        ,  0.        ]])

이제 마지막으로 **Numpy 함수**에 대해서 살펴보고자 한다.

In [64]:
# np.random.randn(a,b)
arr15 = np.random.randn(4,3)
arr15

array([[-1.17451901,  0.0454109 ,  0.2733786 ],
       [-0.18645412, -0.46541234,  0.39666272],
       [ 2.36342188, -0.48288034,  1.93055282],
       [-0.52361912, -1.17516422,  0.82280813]])

In [65]:
# 각 성분의 절댓값 계산 : np.abs()
np.abs(arr15)

array([[1.17451901, 0.0454109 , 0.2733786 ],
       [0.18645412, 0.46541234, 0.39666272],
       [2.36342188, 0.48288034, 1.93055282],
       [0.52361912, 1.17516422, 0.82280813]])

In [66]:
# 각 성분의 제곱근 계산하기 (또는 array ** 0.5 형태로 써도 동일 결과 도출) : np.sqrt()
# 어떤 음수에 대한 제곱근은 일반 실수 체계에서 존재하지 않으므로, nan이 출력
np.sqrt(arr15)

C:\Users\alra\AppData\Local\Temp/ipykernel_1804/1056883480.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr15)


array([[       nan, 0.21309834, 0.52285619],
       [       nan,        nan, 0.62981165],
       [1.53734247,        nan, 1.38944335],
       [       nan,        nan, 0.90708772]])

In [67]:
# 각 성분의 제곱 계산하기
# ~~e+00은 소수점 아래 자릿수가 없는 실수를 의미한다.
np.square(arr15)

array([[1.37949491e+00, 2.06215008e-03, 7.47358581e-02],
       [3.47651404e-02, 2.16608648e-01, 1.57341310e-01],
       [5.58576298e+00, 2.33173424e-01, 3.72703418e+00],
       [2.74176980e-01, 1.38101095e+00, 6.77013216e-01]])

In [68]:
# 각 성분을 무리수 e의 지수로 삼은 값을 계산하기
np.exp(arr15)

array([[ 0.30896755,  1.04645776,  1.31439778],
       [ 0.82989663,  0.62787615,  1.48685435],
       [10.62725448,  0.61700365,  6.89331994],
       [ 0.5923728 ,  0.30876827,  2.27688465]])

In [69]:
# 각 성분에 자연로그를 씌운 값을 계산하기
np.log(arr15)

C:\Users\alra\AppData\Local\Temp/ipykernel_1804/996693603.py:2: RuntimeWarning: invalid value encountered in log
  np.log(arr15)


array([[        nan, -3.09200306, -1.29689764],
       [        nan,         nan, -0.92466894],
       [ 0.86011052,         nan,  0.6578064 ],
       [        nan,         nan, -0.19503224]])

In [70]:
# 각 성분에 밑이 10인 상용로그를 씌운 값을 계산하기
np.log10(arr15)

C:\Users\alra\AppData\Local\Temp/ipykernel_1804/1708328573.py:2: RuntimeWarning: invalid value encountered in log10
  np.log10(arr15)


array([[        nan, -1.34283986, -0.56323549],
       [        nan,         nan, -0.40157862],
       [ 0.37354125,         nan,  0.28568169],
       [        nan,         nan, -0.08470143]])

In [71]:
# 각 성분에 밑이 2인 로그를 씌운 값을 계산하기
np.log2(arr15)

C:\Users\alra\AppData\Local\Temp/ipykernel_1804/947493872.py:2: RuntimeWarning: invalid value encountered in log2
  np.log2(arr15)


array([[        nan, -4.46081747, -1.87102779],
       [        nan,         nan, -1.3340153 ],
       [ 1.24087718,         nan,  0.94901403],
       [        nan,         nan, -0.28137205]])

In [72]:
# 각 성분의 부호 계산하기(+인 경우 1, -인 경우 -1, 0인 경우 0)
np.sign(arr15)

array([[-1.,  1.,  1.],
       [-1., -1.,  1.],
       [ 1., -1.,  1.],
       [-1., -1.,  1.]])

이쯤에서, arr15를 다시 출력하고, 작업을 이어나가자.

In [75]:
arr15

array([[-1.17451901,  0.0454109 ,  0.2733786 ],
       [-0.18645412, -0.46541234,  0.39666272],
       [ 2.36342188, -0.48288034,  1.93055282],
       [-0.52361912, -1.17516422,  0.82280813]])

In [77]:
# 각 성분의 소수 첫 번째 자리에서 올림한 값을 계산하기
np.ceil(arr15)

array([[-1.,  1.,  1.],
       [-0., -0.,  1.],
       [ 3., -0.,  2.],
       [-0., -1.,  1.]])

In [78]:
# 각 성분의 소수 첫 번째 자리에서 내림한 값을 계산하기
np.floor(arr15)

array([[-2.,  0.,  0.],
       [-1., -1.,  0.],
       [ 2., -1.,  1.],
       [-1., -2.,  0.]])

In [80]:
# 각 성분이 NaN인 경우 True를, 아닌 경우 False를 반환하기
np.isnan(arr15)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [81]:
# 각 성분이 nan인 경우 True를, 아닌 경우 False
np.isnan(np.log(arr15))

C:\Users\alra\AppData\Local\Temp/ipykernel_1804/1113276742.py:1: RuntimeWarning: invalid value encountered in log
  np.isnan(np.log(arr15))


array([[ True, False, False],
       [ True,  True, False],
       [False,  True, False],
       [ True,  True, False]])

In [82]:
# 각 성분이 무한대인 경우 True를, 아닌 경우 False
np.isinf(arr15)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [83]:
# 각 성분에 대해 삼각함수 값을 계산할 수 있다(cos, cosh, sin, sinh, tan, tanh).
# 대표로 cos에 대해서만 출력해 보자.
np.cos(arr15)

array([[ 0.38598683,  0.9989691 ,  0.96286422],
       [ 0.98266773,  0.89363659,  0.92235546],
       [-0.7121988 ,  0.88566116, -0.35204632],
       [ 0.86601523,  0.38539154,  0.68016537]])

이전까지는 하나의 array에 적용가능한 함수들을 살펴보았다면, 이번에는 2개의 array에 적용하는 함수들을 살펴볼 것이다.

In [84]:
arr16 = np.random.randn(5,3)
arr16

array([[-0.09450941,  1.00080494, -0.93808477],
       [-0.79982567, -1.41494412, -0.82026073],
       [ 0.85280234, -0.19808432, -0.88018028],
       [-0.56806838, -1.38913571,  1.78970168],
       [-1.60647236, -0.79844887, -1.39672477]])

In [85]:
arr17 = np.random.randn(5,3)
arr17

array([[ 0.8849973 , -1.8234031 , -0.60046975],
       [ 0.18321081,  0.807167  ,  0.12196612],
       [ 0.98147922, -0.7903474 , -0.68675451],
       [ 0.66935089, -0.43873856, -0.23434668],
       [ 0.2566292 ,  1.49803506,  0.0379194 ]])

In [86]:
# 두 개의 array에 대해 동일한 위치의 성분끼리 연산 값을 계산하기(add, subtract, multiply, divide)
# 대표적으로 multiply(곱)에 대해서 살펴보자.
# 동일 성분들끼리 곱이 이루어진다.
np.multiply(arr16,arr17)

array([[-0.08364057, -1.82487083,  0.56329152],
       [-0.14653671, -1.1420962 , -0.10004402],
       [ 0.83700777,  0.15655543,  0.60446778],
       [-0.38023707,  0.6094674 , -0.41941065],
       [-0.41226771, -1.1961044 , -0.05296297]])

In [87]:
# 두 개의 array에 대해 동일한 위치의 성분끼리 비교하여 최대값 또는 최소값 계산(maximum, minimum)
np.maximum(arr16,arr17)

array([[ 0.8849973 ,  1.00080494, -0.60046975],
       [ 0.18321081,  0.807167  ,  0.12196612],
       [ 0.98147922, -0.19808432, -0.68675451],
       [ 0.66935089, -0.43873856,  1.78970168],
       [ 0.2566292 ,  1.49803506,  0.0379194 ]])

통계 함수에 대해서도 알아보자.

통계 함수를 통해 array의 합이나 평균등을 구할 때, 추가로 axis라는 인자에 대한 값을 지정하여 열 또는 행의 합 또는 평균 등을 구할 수도 있다.

In [88]:
arr17

array([[ 0.8849973 , -1.8234031 , -0.60046975],
       [ 0.18321081,  0.807167  ,  0.12196612],
       [ 0.98147922, -0.7903474 , -0.68675451],
       [ 0.66935089, -0.43873856, -0.23434668],
       [ 0.2566292 ,  1.49803506,  0.0379194 ]])

In [89]:
# 전체 성분의 합
np.sum(arr17)

0.8666950060295024

In [90]:
# 열 간의 합
np.sum(arr17, axis=1)

array([-1.53887555,  1.11234394, -0.49562269, -0.00373435,  1.79258365])

In [91]:
# 행 간의 합
np.sum(arr17, axis=0)

array([ 2.97566741, -0.74728699, -1.36168541])

In [92]:
# 전체 성분의 평균 계산
np.mean(arr17)

0.057779667068633495

In [93]:
# 열 간의 평균 계산
np.mean(arr17, axis=1)

array([-0.51295852,  0.37078131, -0.16520756, -0.00124478,  0.59752788])

In [94]:
# 행 간의 평균 계산
np.mean(arr17, axis=0)

array([ 0.59513348, -0.1494574 , -0.27233708])

In [95]:
# 전체 성분의 표준편차, 분산, 최소값, 최대값 계산(std, var, min, max)
# 대표적으로 표준편차를 나타내는 std와, 최솟값을 나타내는 min에 대해서 계산
# 먼저, std를 통해 표준편차 계산해보자.
np.std(arr17)

0.8240102881040449

In [96]:
# 열 간의 최솟값 계산
np.min(arr17, axis=1)

array([-1.8234031 ,  0.12196612, -0.7903474 , -0.43873856,  0.0379194 ])

In [97]:
# 전체 성분의 최소값, 최대값이 위치한 인덱스를 반환(argmin, argmax)
np.argmin(arr17)

1

In [98]:
# 행 간 조건으로 argmax() 적용하기
np.argmax(arr17,axis=0)

array([2, 4, 1], dtype=int64)

In [99]:
# [HARD] 맨 처음 성분부터 각 성분까지의 누적합 또는 누적곱을 계산(cumsum, cumprod)
np.cumsum(arr17)

array([ 0.8849973 , -0.9384058 , -1.53887555, -1.35566473, -0.54849773,
       -0.42653161,  0.55494761, -0.23539979, -0.9221543 , -0.25280341,
       -0.69154196, -0.92588865, -0.66925945,  0.8287756 ,  0.86669501])

In [100]:
np.cumprod(arr17)

array([ 8.84997298e-01, -1.61370681e+00,  9.68982121e-01,  1.77528002e-01,
        1.43294745e-01,  1.74771046e-02,  1.71534149e-02, -1.35571568e-02,
        9.31043859e-03,  6.23195033e-03, -2.73419689e-03,  6.40749974e-04,
        1.64435151e-04,  2.46329620e-04,  9.34067171e-06])

In [101]:
# 열 간으로 제한해서 누적합 계산하기 (해당 행 안에서만 누적합 적용)
np.cumsum(arr17,axis=1)

array([[ 0.8849973 , -0.9384058 , -1.53887555],
       [ 0.18321081,  0.99037782,  1.11234394],
       [ 0.98147922,  0.19113182, -0.49562269],
       [ 0.66935089,  0.23061233, -0.00373435],
       [ 0.2566292 ,  1.75466425,  1.79258365]])

마지막으로, 기타 다른 함수 몇 개만 더 살펴보자.

In [102]:
arr18 = np.random.randn(4,2)
arr18

array([[ 1.60021161, -1.10205749],
       [ 1.02833778, -0.47774083],
       [-0.04284378,  1.93740159],
       [-0.91031991, -1.05402196]])

In [103]:
# 전체 성분에 대해서 오름차순으로 정렬 (행단위 체크)
np.sort(arr18)

array([[-1.10205749,  1.60021161],
       [-0.47774083,  1.02833778],
       [-0.04284378,  1.93740159],
       [-1.05402196, -0.91031991]])

In [104]:
# 다음 결과도 위의 코드와 출력되는 결과가 같다.
np.sort(arr18,axis=1)

array([[-1.10205749,  1.60021161],
       [-0.47774083,  1.02833778],
       [-0.04284378,  1.93740159],
       [-1.05402196, -0.91031991]])

In [105]:
# 행 방향으로 오름차순으로 정렬 (열단위 체크)
np.sort(arr18,axis=0)

array([[-0.91031991, -1.10205749],
       [-0.04284378, -1.05402196],
       [ 1.02833778, -0.47774083],
       [ 1.60021161,  1.93740159]])